config/routes.rb
Rails.application.routes.draw do
  resources :schools, :only => [:index, :create, :update, :edit]

  namespace 'admin' do
    resources :schools do
      member do
        get "migration/new", :action => :new_migration
        get "migration/:target_school_id/confirm", :action => :confirm_migration, :as => 'confirm_migration'
        post "migration/:target_school_id", 
             :action => :create_migration, 
             :constraints => { :target_school_id => /\d+/ }, 
             :as => 'create_migration'
      end
    end
  end

  # non-production routes
  unless Rails.env.production?
    namespace 'test' do
      get 'scidea_schools_qunit_tests', :to => 'scidea_schools_qunit_tests#index'
      get 'scidea_schools_qunit_tests/*test_names', :to => 'scidea_schools_qunit_tests#index'    
    end
  end

end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :profiles

  # approved field deliberately excluded so public-facing users cannot maliciously approve bad schools
  attr_accessible :address_1, :address_2, :city, :name, :state, :zipcode, :phone

  validates_presence_of :address_1
  validates_presence_of :city
  validates_presence_of :name
  validates_presence_of :state
  validates_presence_of :zipcode
  validates_presence_of :phone

  validate :zipcode_formatting
  validate :phone_formatting
  
  before_destroy :do_not_delete_if_dependencies

  ZIPCODE_PATTERN = /^[\d]{5}$/

  # Class methods

  def self.render_form?
    count > 0 and Audience.count > 0
  end
  
  # handles zipcode searches from learner-side forms; will filter out schools
  # that are not approved by the admin UNLESS that school is passed via the
  # user_created_school parameter, which allows the unapproved school created
  # by the current user to be returned as a part of the search query
  def self.learner_form_search(zipcode, user_created_school = nil)
    return [] unless zipcode && zipcode.match(ZIPCODE_PATTERN)

    conditions = "zipcode = #{zipcode} AND approved = true"
    
    # the school user created should be included in the return list only if conditions below are met
    conditions += " OR id = #{user_created_school.id}" if user_created_school &&
        user_created_school.zipcode == zipcode && !user_created_school.approved

    School.all(:conditions => conditions, :order => "name asc")
  end

  def self.search(name_or_zipcode)
    name_or_zipcode ? where('name LIKE ? OR zipcode LIKE ?', "%#{name_or_zipcode}%", "%#{name_or_zipcode}%") : scoped
  end

  def self.without_school(school)
    where('schools.id != ?', school.id)
  end
  
  # Instance methods

  # moves all users associated with this school to school parameter, returns
  # an array of all users migrated from this school to the school parameter
  def migrate_users_to(school)
    raise ArgumentException unless school

    profiles.map do |profile| 
      profile.school = school
      profile.save
      profile.user # returned through method call via an array (from map)
    end
  end

  def phone=(val)
    write_attribute :phone, val.nil? ? '' : val.split(//).select{|char| char.match(/^\d$/) }.join.gsub(/^1/, '')
  end

  def phone
    p = read_attribute :phone
    (p.nil? || p.size < 10) ? p : "(#{p[0,3]}) #{p[3,3]}-#{p[6,4]}#{p.size > 10 ? 'x' + p[10..-1]: ''}"
  end

  def to_client_model_json
    to_json :except => [:created_at, :updated_at]
  end

  def user_count
    profiles.count
  end

  private

  def phone_formatting
    errors[:phone] << "must be at least 10 digits long" unless self.phone.nil? || self.phone.empty? || self.phone.size >= 10
  end

  def zipcode_formatting
    errors.add(:zipcode, "must be five numbers") unless zipcode && zipcode.match(ZIPCODE_PATTERN)
  end
  
  def do_not_delete_if_dependencies
    # if any users have this school, do not delete it
    if self.profiles.count > 0
      self.errors.add(:base, "Educational institution #{self.name} was not deleted because it is tied to user profiles. Before deleting #{self.name} use the migration feature to migrate these users to other educational institutions.")
      return false
    end
  end

end

app/controllers/admin/schools_controller.rb
module Admin
  class SchoolsController < AdminController

    ssl_exceptions

    before_filter :authenticate_user!
    authorize_resource

    include ::ActionView::Helpers::TextHelper
    
    has_widgets do |root|
      root << widget(:paginated_list) << widget(:datatable)
    end

    def initialize
      super
      @sort_columns = %w[name city state zipcode approved]
    end

    # GET /schools
    def index
      @schools = School.search(params[:search]).
                        order(sort_column + ' ' + sort_direction).
                        paginate(:per_page => per_page, :page => params[:page])
    end

    # GET /schools/1
    def show
      @school = School.where("id = ?", params[:id]).first
    end

    # GET /schools/new
    def new
      @school = School.new :approved => true
    end

    # GET /schools/1/edit
    def edit
      @school = School.where("id = ?", params[:id]).first
    end

    # POST /schools
    def create
      @school = School.new(params[:school])
      
      check_school_approved(@school, params)

      if @school.save
        redirect_to(admin_school_path(@school), :flash => { :success => "Educational institution was successfully created." })
      else
        render :action => "new"
      end
    end

    # PUT /schools/1
    def update
      @school = School.where("id = ?", params[:id]).first

      check_school_approved(@school, params)

      if @school.update_attributes(params[:school])
        redirect_to(admin_school_path(@school), :flash => { :success => "Educational institution was successfully updated." })
      else
        render :action => "edit"
      end
    end

    # DELETE /schools/1
    def destroy
      @school = School.where("id = ?", params[:id]).first
      if @school.destroy
        flash_message = { :success => "Educational institution was successfully deleted." }
      else
        if @school && @school.errors[:base] && @school.errors[:base].count > 0
          flash_message = { :failure => @school.errors[:base].first }
        else
          flash_message = { :failure => "Educational Insitution could not be deleted" }
        end
      end
      redirect_to(admin_schools_path, :flash => flash_message)
    end

    # GET /schools/1/migration/new
    def new_migration
      @school = School.where("id = ?", params[:id]).first

      @target_schools = School.search(params[:search]).
                               without_school(@school).
                               order(sort_column + ' ' + sort_direction).
                               paginate(:per_page => per_page, :page => params[:page])
    end

    # GET /schools/1/migration/2/confirm
    def confirm_migration
      @school = School.where("id = ?", params[:id]).first
      @target_school = School.where("id = ?", params[:target_school_id]).first
    end

    # POST /schools/1/migration/2
    def create_migration
      @school = School.where("id = ?", params[:id]).first
      @target_school = School.where("id = ?", params[:target_school_id]).first

      migrated_users = @school.migrate_users_to(@target_school) if @school && @target_school

      if @school && @target_school && migrated_users.size >= 0
        redirect_to(admin_schools_path, :flash => { :success => "Successfully migrated #{pluralize(migrated_users.size, 'user')} " +
                                                               "from #{@school.name} to #{@target_school.name}." }) 
      else
        flash[:error] = "Unable to migrate users between educational institution"
        @target_schools = School.search(params[:search]).
                                 without_school(@school).
                                 order(sort_column + ' ' + sort_direction).
                                 paginate(:per_page => per_page, :page => params[:page])
        render :new_migration
      end
    end
    
    private

    def check_school_approved(school, params)
      if params[:school] && params[:school][:approved]
        school.approved = params[:school][:approved] == '1' 
      end
    end

  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  ssl_exceptions
  authorize_resource
  
  def index
    @selected_school = params[:new_school_id] ? School.where("id = ?", params[:new_school_id]).first : nil
    @schools = School.learner_form_search(params[:zipcode], @selected_school)

    render_success
  end

  def create
    @school = School.new params[:school]

    @school.approved = current_user && current_user.is_admin?

    if @school && @school.save
      render :json => @school.to_client_model_json
    else
      render_error
    end
  end
  
  def update
    @school = School.where("id = ?", params[:id]).first

    if @school && @school.update_attributes(params[:school])
      # @schools = School.learner_form_search(@school.zipcode, @school)
      # @selected_school = @school
      render :json => @school.to_client_model_json
      # render_success
    else
      render_error
    end
  end

  def edit
    @school = School.where("id = ?", params[:id]).first

    render :partial => 'form', :layout => false
  end

  private
  def render_success
    render :json => { 
        :status => :ok, 
        :html => render_to_string(:partial => 'search')
      }.to_json 
  end

  def render_error
    render :status => 400, :json => {
        :status => :error,
        :message => 'Your educational institution could not be saved. Please review the form and verify all required fields are completed',
        :html => render_to_string(:partial => 'form.html')
      }.to_json
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper

  def school_selected_id(school, params)
    if school && !school.new_record?
      school.id
    elsif params[:user] and params[:user][:profile_attributes] and params[:user][:profile_attributes][:school_id]
      params[:user][:profile_attributes][:school_id]
    else
      ''
    end
  end

  def school_select_zipcode(school, params)
    if school && !school.new_record?
      school.zipcode
    else
      params[:school_zipcode] || ''
    end
  end

end

app/views/admin/schools/_form.html.erb
<%= render :partial => 'shared/form_errors', :locals => { :object => @school } %>

<%= semantic_form_for ['admin', @school] do |f| %>

  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :address_1 %>
    <%= f.input :address_2 %>
    <%= f.input :city %>
    <%= f.input :state, :as => :select, :collection => GeographicalRegions.all_us_states_as_select_field_pairs %>
    <%= f.input :zipcode, :input_html => { :maxlength => '5' } %>
    <%= f.input :phone %>
    <%= f.input :approved %>
  <% end %>
          
  <%= f.buttons do %>
    <%= f.commit_button "Submit" %>
  <% end %>

<% end %>

app/views/admin/schools/_school.html.erb
 <div class="school-address">
  <%= school.name %><br />
  <%= school.address_1 %><br />
  <% if school.address_2 && !school.address_2.empty? %>
    <%= school.address_2 %><br />
  <% end %>

  <%= school.city %>, <%= school.state %> <%= school.zipcode %><br />
  <%= school.phone %>
 </div>

app/views/admin/schools/_search.html.erb
<%= form_tag form_url, :method => 'get', :id => "listview_search", :role => 'search' do %>  
  <%= hidden_field_tag :direction, params[:direction] %>  
  <%= hidden_field_tag :sort, params[:sort] %>
  <%= hidden_field_tag :per_page, params[:per_page] %>  
  <ol id="schools-search">
    <li>
      <label for="search">Search by Name or Zipcode</label>
      <%= text_field_tag :search, params[:search], { :placeholder => 'e.g., Eastern High School, 12345' } %> 
    </li>
    <li>
      <%= submit_tag "Search", :name => nil %>
    </li>
  </ol>
<% end %>

app/views/admin/schools/confirm_migration.html.erb
<% page_title 'Confirm User Migration between Educational Institutions' %>

<p><%= pluralize(@school.user_count, 'user') %> will be migrated from</p>

<%= render :partial => 'school', :locals => { :school => @school } %>
<p>to</p>
<%= render :partial => 'school', :locals => { :school => @target_school } %>

<p>Are you sure you want to do this?</p>

<%= form_tag create_migration_admin_school_path(@school, @target_school) do %>
  <%= hidden_field_tag :school_id, @school.id %>
  <%= hidden_field_tag :target_school_id, @target_school.id %>
  <%= submit_tag("Yes, Migrate Users") %> | 
  <%= link_to "No, Choose a Different Institution", migration_new_admin_school_path(@school) %> |
  <%= link_to 'Manage Educational Institutions', admin_schools_path %>
<% end %>

app/views/admin/schools/edit.html.erb
<% page_title 'Editing Educational Institution' %>

<%= render 'form' %>

<%= link_to 'Migrate Users to Different Educational Institution', migration_new_admin_school_path(@school) %> |
<%= link_to 'Show', admin_school_path(@school) %> |
<%= link_to 'Manage Educational Institutions', admin_schools_path %>

app/views/admin/schools/index.html.erb
<% css do %>
  <%= theme_css 'layouts/index', :media => 'screen' %>
<% end %>

<% page_title 'Manage Educational Institutions' %>

<%= render :partial => 'search', :locals => { :form_url => admin_schools_path, :params => params } %>

<%= render_widget :paginated_list, :display, {
  :collection => @schools,
  :entry_name => 'educational institution',
  :css_class => "",
  :id => "schools-found",
  :list_renderer => [
    :datatable,
    {
      :columns => [
        {
          :label => "Name",
          :content => lambda{|item| link_to item.name, admin_school_path(item) },
          :sort => 'name',
          :width => "200px"
        },
        {
          :label => "City",
          :content => :city,
          :sort => 'city',
          :width => "150px"
        },
        {
          :label => "State",
          :content => :state,
          :sort => 'state',
        },
        {
          :label => "Zipcode",
          :content => :zipcode,
          :sort => 'zipcode'
        },
        {
          :label => "Approved",
          :content => lambda{ |item| item.approved ? 'Yes' : 'No' },
          :sort => 'approved'
        },
        :actions => [
          :edit, 
          :delete
        ]
      ],
      :actions_are_admin => true,
      :css_class => 'datatable',
      :sort_column => sort_column
    }
  ],
  :header => {
    :css_class => 'plain'
  },
  :navigation => {}
} %>
<%= link_to 'New Educational Institution', new_admin_school_path %>

app/views/admin/schools/new.html.erb
<% page_title 'New Educational Institution' %>

<%= render 'form' %>

<%= link_to 'Back', admin_schools_path %>

app/views/admin/schools/new_migration.html.erb
<% css do %>
  <%= theme_css 'layouts/index.css', :media => 'screen' %>
  <%= stylesheet_link_tag 'scidea/admin/pages/schools/user_migrate' %>
<% end %>

<% page_title 'Migrate Users between Educational Institutions' %>

<div id="school-migration-message">
  <p>You are migrating users from:</p>
  <%= render :partial => 'school', :locals => { :school => @school } %>
</div>

<p>Choose the educational institution to which you would like to migrate users.</p>

<hr>

<%= render :partial => 'search', :locals => { 
    :form_url => migration_new_admin_school_path(@school),
    :params => params } %>

<%= render_widget :paginated_list, :display, {
  :collection => @target_schools,
  :entry_name => 'educational institution',
  :css_class => "",
  :id => "schools-found",
  :list_renderer => [
    :datatable,
    {
      :columns => [
        {
          :label => "Name",
          :content => :name,
          :sort => 'name',
          :width => "300px"
        },
        {
          :label => "City",
          :content => :city,
          :sort => 'city',
        },
        {
          :label => "State",
          :content => :state,
          :sort => 'state',
        },
        {
          :label => "Zipcode",
          :content => :zipcode,
          :sort => 'zipcode'
        },
        {
          :label => "Users",
          :content => :user_count,
          :sort => 'user_count'
        },
        {
          :label => "Approved",
          :content => lambda{ |item| item.approved ? 'Yes' : 'No' },
          :sort => 'approve'
        },
        :actions => [
          lambda {|item|
            link_to 'Choose', confirm_migration_admin_school_path(@school, item), :class => 'do-choose', :title => "Choose"
          }
        ]
      ],
      :css_class => 'datatable',
      :sort_column => sort_column
    }
  ],
  :header => {
    :css_class => 'plain'
  },
  :navigation => {}
} %>
<%= link_to 'Manage Educational Institutions', admin_schools_path %>

app/views/admin/schools/show.html.erb
<% page_title 'Educational Institution Detail' %>

<p>
  <b>Name</b>:
  <%= @school.name %>
</p>

<p>
  <b>Address</b>:
  <%= @school.address_1 %>
</p>

<p>
  <b>Address 2</b>:
  <%= @school.address_2 if @school.address_2 && !@school.address_2.empty? %>
</p>

<p>
  <b>City</b>:
  <%= @school.city %>
</p>

<p>
  <b>State</b>:
  <%= GeographicalRegions.us_state_by_abbreviation @school.state %>
</p>

<p>
  <b>Zipcode</b>:
  <%= @school.zipcode %>
</p>

<p>
  <b>Phone</b>:
  <%= @school.phone %>
</p>

<p>
  <b>Approved</b>:
  <%= @school.approved ? 'Yes' : 'No' %>
</p>


<%= link_to 'Edit', edit_admin_school_path(@school) %> |
<%= link_to 'Migrate Users to Different Educational Institution', migration_new_admin_school_path(@school) %> |
<%= link_to 'Manage Educational Institutions', admin_schools_path %>